### ISSUE TITLE
Mutable default values for arguments

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/flask-resources#114]
Package version (if known): 1.0.0

## Describe the bug
It looks like there's some mutable objects used as default values for some function arguments, e.g. a [dictionary literal here](https://github.com/inveniosoftware/flask-resources/blob/master/flask_resources/serializers/base.py#L48).
Chances are that this is [unintentional and basically a pitfall](https://towardsdatascience.com/python-pitfall-mutable-default-arguments-9385e8265422) that I think every Python programmer has fallen into at some point.

Unless this is intended, we should change the default values for arguments to something non-mutable.

**Comment by ntarocco** [comment]
My findings:
- https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/utils.py#L171
- https://github.com/inveniosoftware/invenio-pages/blob/master/invenio_pages/services/service.py#L52
- https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/oaiserver/services/services.py#L38
- https://github.com/inveniosoftware/flask-resources/blob/master/flask_resources/resources.py#L31
- https://github.com/inveniosoftware/flask-resources/blob/master/flask_resources/serializers/base.py#L48

**Comment by max-moser** [comment]
Thanks a lot! :ok_hand:

**Comment by ppanero** [comment]
merged flask-resources, re-opening for the rest
