### ISSUE TITLE
[Decision] Name `ResourceRequestCtx` better

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/flask-resources#2]
Decision will affect: 
- https://github.com/inveniosoftware/flask-resources/issues/4
- https://github.com/inveniosoftware/flask-resources/issues/8
- ...

**Question that needs answer:**

The concept of `controller` is only known to the `invenio-resources` module. Those have a fully defined API (input parameters --> returned objects).

This means that in the jump from resource to contoller the `ResourceRequestCtx` is getting stripped in the necessary attributes for the controller, and not passed forward. Being this the case, the following questions need to be answered:

1- Do we actually need said object, or can we do with the `resquest` object that is already present in Flask. From what can be seen in the *current* code (might change in the future) only a few more attributes are needed (content and accepted mimetypes). Most of the rest (record pid, user) could be passed to the resource using decorators.

2- If we actually need it, who is in charge of adding content to it.

*The question related to "if this solved the information deprivation", which is yes, is answered in the context below*

**Context from #1**
@fenekku: From discussion: this ResourceRequestCtx is just a namespace over some of the request's information. It is stuck onto the global g object instead of being passed down. The "global" object pattern is something Flask uses frequently so we are in keeping with Flask. It's not passed down directly, because sometimes a layer in the call hierarchy doesn't pass it down and then a layer much deeper is deprived of it. By using a global object, any layer will always have access to it. However see 3rd point at the end.

So the above code is just a "nicety": it set ups this namespaced object and tears it down when the part of the request under management by flask_resources is done.

The unclear stuff:

1- what makes the cut in this object and what doesn't?
2- Who fills it up?
3- Flask-resources is all about organizing your REST API flow for you and down the line passing the content of ResourceRequestCtx into controllers via arguments. In other words, at the very moment where we are transferring business logic control, we are choosing to not use the global object so that we can decouple from the request flow. This means that the "inaccessible to lower layer problem" rears itself up again if we pick and choose arguments to send... Now I'm actually fine with using the global object until this point: who knows how many layers the flask/invenio-resources flow takes and which layer needs what! But at the time of passing arguments to the controller, I think passing a wholesale serialized version of this ResourceRequestCtx might avoid the "inaccessible to lower layer problem" as far as what we have control over is concerned. At this point the controller has everything we could give (it's as supported as it could be). And when control flow goes back to the resources-managed code, we still have access to the global object so we are good!

But again I have only looked at this repo, so I might be misunderstanding some things (potential confusion: I am thinking that the controller is the business logic inside what Flask calls a view - I am thinking of controller as in MVC and hoping this is what the controller we talked about is that).

@ppanero: Let's chat about this in person, it might be easier. The two first points you ask are totally valid but there is no "strong" answer right now, since this is still work in progress and those are some of the questions we are trying to address.

As for the third point, from my perspective, the "inaccessible to lower layer problem" is two folded:

a) Something is inaccesible
b) Should that something actually be needed? Or are we using wrong attributes since they belong to another scope?

Therefore:

1- First step. As you mentioned the ResourceRequestCtx gets into the resource, which is the "entity". Here is where the two first questions apply.
2- Second step. The ResourceRequestCtx gets striped and only certain attribtues are passed to the controller. This is done because otherwise we are just "tunneling" the problem and it will make things dependent on each other later on the road. Being the problem that something (e.g. current_user) should not get to the controller and only a derived of it (e.g. "user is authenticated") and all this operations should be calculated by the resouce. The controller should only be in charge of the bussiness logic (e.g. "If the user is authenticated create the record in DB, index it, etc.).

But as said let's chat about this in person, it might be easier.

**EDIT**
- [ ] Naming of and in resource_requestctx` should be revisited: short, flexible to any context, but representative would be best.
- [x] ~~use Flask's ext approach: https://flask.palletsprojects.com/en/1.1.x/extensiondev/#the-extension-code~~ no immediate benefit
- [x] ~~merge `with_route` decorator into part of its loading~~ no immediate benefit

**Comment by fenekku** [comment]
Yes during the conversation we can elucidate some of those points.

- "What is actually needed?" is a good question
- For the "inaccessible to lower layer problem", I was reading through the docs: https://flask.palletsprojects.com/en/1.1.x/extensiondev/#the-extension-code and this might be the approach for our situation (it gives us the ResourceRequestCtx  for free if we follow the `init_app` template...) Something like:

```python
from flask_resources import resource  # is a global proxy now

class Resource():
    def get():
        do_something(resource)
        controller.get()

class Controller():
    def get():
        do_something_else(resource)  # has the result of do_something_with_resource() from above now
```

Naming not ideal but you get the idea I hope.

This `ctx = _app_ctx_stack.top` in the doc is especially nice. Gives us the namespacing in the current context no matter what it is. So in tests we just need to push a regular request context or application context and get that namespace up.
